version: '3'

services:

  micrometer:
    image: micrometer
    container_name: micrometer
    ports:
        - 8080:8080
    networks:
      micrometer-network:
        ipv4_address: 20.5.0.2

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
        - 9090:9090
    volumes:
        - ./configuration/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      micrometer-network:
        ipv4_address: 20.5.0.3

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./configuration/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      micrometer-network:
        ipv4_address: 20.5.0.4

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'micrometer'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      micrometer-network:
        ipv4_address: 20.5.0.5

networks:
   micrometer-network:
     driver: bridge
     ipam:
      config:
        - subnet: 20.5.0.0/16
