spring:
  application:
    name: micrometer
  datasource:
    url: jdbc:mysql://mysql:3306/micrometer
    username: user
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: micrometer-hikari-pool
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

environment: production

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
debug: true
