global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'micrometer'
    scrape_interval: 5s
    static_configs:
      - targets: ['micrometer:8080']
    metrics_path: /actuator/prometheus
